name: Validation CI

on:
  push:
    branches: [ "main" ]

jobs:
  verifier_code:
    runs-on: ubuntu-latest
    steps:
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Installer les dépendances de test
        run: pip install pytest # <-- Étape de correction
      - name: Lancer les tests
        run: python -m pytest test_app.py